### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by htwang14** [YiZeng623/I-BAU#1]
Dear authors, 

Thanks for releasing the codes! Could you please provide instructions on how to run the codes to reproduce the results? For example, what is the command to defense the BadNet attack on CIFAR10?

Thanks in advance.

**Comment by YiZeng623** [comment]
Hi there, thanks for the interest in our work! We will provide an updated version of the readme file, providing you with more instructions and an off-the-shelf function in the following days ASAP.

For now, we have provided two jupyter notebook files that you can directly play with. We have included the pre-trained poisoned model in the checkpoint so that you do not have to train a poisoned model from scratch.

By following 'clean_solution_..._cifar.ipynb', you can reproduce the results on a badnets poisoned cifar model. The other file ending with 'GTSRB' is a demo of unlearning a torjan_WM poisoned model. You can try our I-BAU on more attack cases by switching the dataset and deploying the pre-trained weights from the checkpoint folder. Enjoy!

**Comment by YiZeng623** [comment]
> Dear authors,
> 
> Thanks for releasing the codes! Could you please provide instructions on how to run the codes to reproduce the results? For example, what is the command to defense the BadNet attack on CIFAR10?
> 
> Thanks in advance.

Hi there,

I want to let you know that we have updated the readme file. Hopefully, you can have fun with this project:)

If you have regeistered for the ICLR 2022, you can follow this \[[link](https://iclr.cc/virtual/2022/poster/6180)\] to jointhe live chat with us on Wed 27, Apr 12:30 p.m. EST.

Any further questions are welcome.

Yi

**Comment by htwang14** [comment]
That looks cool! Thanks for the update :)

**Comment by htwang14** [comment]
Hi Yi, I got another quick question. Is the pattern used for smooth attack the same with [the one you released in the other repo](https://github.com/YiZeng623/frequency-backdoor/blob/main/Sec5_Smooth_Trigger/data/best_universal.npy)? Also, could you please share the smooth pattern for GTSRB Dataset (the pinkish one shown in the paper). I suppose the smooth pattern on different datasets are not exchangeable, right? Thanks a lot!

**Comment by YiZeng623** [comment]
Yes, each trigger are dataset and model (might impair a little bit one the attack effects) specific actually. If you want to use the triggers in that repo, you need to make sure 

1. you use the same dataset of images ranging (input's value range) from (0,1); 
2. using the same DNN structure as that repo:)

BTW, I just added the GTSRB smooth trigger from that work for you: [https://github.com/YiZeng623/frequency-backdoor/blob/99a16a7939ed5ca17848f6c70a5072442ef5b9f2/Sec5_Smooth_Trigger/data/gtsrb_universal.npy]

**Comment by htwang14** [comment]
Thank you so much! Actually, I have observed Smooth attack has pretty good transferability across different model structures. Using the pattern released in your repo (which I suppose is generated by some Inception model) can achieve 97% attack success rate on WRN16. I think such good transferability is a good thing for the attack, since the attacker may not know what models the users would apply. Please correct me if I'm wrong.
